TEMPLATE = lib
CONFIG += log4qt-buildlib
QT += core xml network sql
QT -= gui

include(libLog4Qt.pri)

TARGET = $$LIBLOG4QT_NAME
DESTDIR = $$PROJECT_LIBDIR

LOG4QT_VERSION_MAJOR = 1
LOG4QT_VERSION_MINOR = 1
LOG4QT_VERSION_RELEASE = 0

LOG4QT_VERSION = '\\"$${LOG4QT_VERSION_MAJOR}.$${LOG4QT_VERSION_MINOR}.$${LOG4QT_VERSION_RELEASE}\\"'
DEFINES += LOG4QT_VERSION_STR=\"$${LOG4QT_VERSION}\"
DEFINES += LOG4QT_VERSION=$${LOG4QT_VERSION}
